name: Deploy VK Mini App
on:
  push:
    branches: 
      - dev
      - main
jobs:
  deploy:
    env:
      NODE_VERSION: 14.x
      MINI_APPS_ACCESS_TOKEN: ${{ secrets.SERVICE_TOKEN }}
      MINI_APPS_ENVIRONMENT: ${{ github.ref == 'refs/heads/dev' && 'dev' || 'production' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Deploy on ${{ github.ref == 'refs/heads/dev' && 'dev' || 'production' }}
      run: |
        npm ci 
        sh -c 'timeout 5m npm run deploy' || true


